In [312]:
import pandas as pd
import matplotlib as mpl

In [313]:
# 1) Pandas program to read the given csv file.

data = pd.read_csv('data/AfricaCupofNationsMatches.csv')

In [314]:
# 2) get the first 7 rows of your data frame.
data.head(7)

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0
5,1959,29-May-59,NaN,Egypt,Sudan,2.0,1.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
6,1962,14-Jan-62,NaN,Ethiopia,Tunisia,4.0,2.0,Semifinals,NaN,Hailé Sélassié Stadium,Addis Ababa,30000.0

In [315]:
# 3) select the ‘HomeTeam’, ‘AwayTeam’, ‘HomeTeamGoals’ and ‘AwayTeamGoals’ 
query = data[['HomeTeam', 'AwayTeam', 'HomeTeamGoals', 'AwayTeamGoals']]

print(query)

        HomeTeam       AwayTeam  HomeTeamGoals  AwayTeamGoals
0         Sudan           Egypt            1.0            2.0
1      Ethiopia    South Africa            NaN            NaN
2         Egypt        Ethiopia            4.0            0.0
3          Egypt       Ethiopia            4.0            0.0
4         Sudan        Ethiopia            1.0            0.0
..           ...            ...            ...            ...
617  Madagascar         Tunisia            0.0            3.0
618     Senegal         Tunisia            1.0            0.0
619     Algeria         Nigeria            2.0            1.0
620     Tunisia         Nigeria            0.0            1.0
621     Senegal         Algeria            0.0            1.0

[622 rows x 4 columns]

In [316]:
# 4) select the rows where Egypt appears.

In [317]:
# 5) count the number of rows and columns of your data frame.
data.shape

(622, 12)

In [318]:
# 6)  select the rows where the ‘Attendance’ is missing.
columns_headers = data.columns.values
data.loc[data['Attendance'].isna(), columns_headers]

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
8,1962,20-Jan-62,NaN,Tunisia,Uganda,3.0,0.0,Third place match,NaN,Hailé Sélassié Stadium,Addis Ababa,NaN
9,1962,21-Jan-62,NaN,Ethiopia,Egypt,4.0,2.0,Final,win after extra time,Hailé Sélassié Stadium,Addis Ababa,NaN
10,1963,24-Nov-63,NaN,Ghana,Tunisia,1.0,1.0,Group A,NaN,Accra Sports Stadium,Accra,NaN
11,1963,26-Nov-63,NaN,Ghana,Ethiopia,2.0,0.0,Group A,NaN,Accra Sports Stadium,Accra,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
565,2017,29 January 2017 (2017-01-29),20:00,Egypt,Morocco,1.0,0.0,Quarter-finals,NaN,Stade de Port-Gentil,Port-Gentil,NaN
566,2017,1 February 2017 (2017-02-01),20:00,Burkina Faso,Egypt,1.0,1.0,Semi-finals,Egypt win on Penalities 3-4,Stade de l'Amitié,Libreville,NaN
567,2017,2 February 2017 (2017-02-02),20:00,Cameroon,Ghana,2.0,0.0,Semi-finals,NaN,Stade de Franceville,Franceville,NaN
568,2017,4 February 2017 (2017-02-04),20:00,Burkina Faso,Ghana,1.0,0.0,Third place play-off,NaN,Stade de Port-Gentil,Port-Gentil,NaN
569,2017,5 February 2017 (2017-02-05),20:00,Egypt,Cameroon,1.0,2.0,Final,NaN,Stade de l'Amitié,Libreville,NaN

In [319]:
# 7) select the rows where the ‘HomeTeamGoals’ are between 3 and 6 inclusive.
between_3_4 = data.loc[(data['HomeTeamGoals'] >3 )&(data['HomeTeamGoals'] <=6),columns_headers]
print(between_3_4)

     Year                      Date   Time            HomeTeam  \
2    1957                  16-Feb-57    NaN             Egypt
3    1959                  22-May-59    NaN              Egypt
6    1962                  14-Jan-62    NaN          Ethiopia
9    1962                  21-Jan-62    NaN          Ethiopia
12   1963                  28-Nov-63    NaN          Ethiopia
13   1963                  24-Nov-63    NaN              Egypt
15   1963                  28-Nov-63    NaN             Sudan
18   1965                  12-Nov-65    NaN           Tunisia
20   1965                  19-Nov-65    NaN           Senegal
21   1965                  12-Nov-65    NaN             Ghana
23   1965                  19-Nov-65    NaN             Ghana
29   1968                  14-Jan-68    NaN           Algeria
39   1968                  19-Jan-68    NaN             Ghana
46   1970                  10-Feb-70    NaN       Ivory Coast
49   1970                   7-Feb-70    NaN  United Arab Rep.
69   1972                  29-Feb-72    NaN             Congo
72   1972                   4-Mar-72    NaN          Cameroon
85   1974                   7-Mar-74    NaN             Zaire
97   1976                   1-Mar-76    NaN           Nigeria
106  1976                  11-Mar-76    NaN            Guinea
110  1978                   5-Mar-78    NaN           Nigeria
159  1984                   7-Mar-84    NaN          Cameroon
205  1990                   2-Mar-90    NaN           Algeria
245  1994                  28-Mar-94    NaN             Egypt
247  1994                  27-Mar-94    NaN       Ivory Coast
258  1994                   6-Apr-94    NaN            Zambia
270  1996                  20-Jan-96    NaN            Zambia
272  1996                  24-Jan-96    NaN            Zambia
303  1998                   8-Feb-98  18:00       Ivory Coast
306  1998                  16-Feb-98  20:00       Ivory Coast
307  1998                  16-Feb-98  20:00      South Africa
310  1998                  13-Feb-98  17:00             Egypt
320  1998                  27-Feb-98  16:00          DR Congo
338  2000                   2-Feb-00  17:00             Egypt
340  2000                  23-Jan-00  16:00           Nigeria
400  2004                  29-Jan-04  16:30          Cameroon
406  2004                  31-Jan-04  14:00           Nigeria
407  2004                  31-Jan-04  18:00           Morocco
415  2004                  11-Feb-04  19:00           Morocco
430  2006                  22-Jan-06  17:15           Tunisia
443  2006                   3-Feb-06  19:00             Egypt
458  2008                  25-Jan-08  17:00       Ivory Coast
462  2008                  22-Jan-08  17:00             Egypt
464  2008                  26-Jan-08  17:00          Cameroon
475  2008                   3-Feb-08  20:30       Ivory Coast
480  2008                   9-Feb-08  17:00             Ghana
482  2010                  10-Jan-10  20:00            Angola
595  2019  24 June 2019 (2019-06-24)  22:00              Mali

                 AwayTeam  HomeTeamGoals  AwayTeamGoals              Stage  \
2                Ethiopia            4.0            0.0              Final
3                Ethiopia            4.0            0.0   Final Tournament
6                 Tunisia            4.0            2.0         Semifinals
9                   Egypt            4.0            2.0              Final
12                Tunisia            4.0            2.0            Group A
13                Nigeria            6.0            3.0            Group B
15                Nigeria            4.0            0.0            Group B
18               Ethiopia            4.0            0.0            Group A
20               Ethiopia            5.0            1.0            Group A
21    Congo-Léopoldville            5.0            2.0            Group B
23            Ivory Coast            4.0            1.0            Group B
29                 Uganda            4.0            0.0            Group A
39            Ivory Coast            4.0            3.0        Semi-finals
46               Ethiopia            6.0            1.0            Group A
49                 Guinea            4.0            1.0            Group B
69                  Sudan            4.0            2.0            Group B
72                  Zaire            5.0            2.0  Third place match
85              Mauritius            4.0            1.0            Group B
97                  Zaire            4.0            2.0            Group B
106                 Egypt            4.0            2.0            Group B
110           Upper Volta            4.0            2.0            Group A
159                  Togo            4.0            1.0            Group A
205               Nigeria            5.0            1.0            Group A
245                 Gabon            4.0            0.0            Group B
247          Sierra Leone            4.0            0.0            Group C
258                  Mali            4.0            0.0         Semifinals
270          Burkina Faso            5.0            1.0            Group B
272          Sierra Leone            4.0            0.0            Group B
303               Namibia            4.0            3.0            Group C
306                Angola            5.0            2.0            Group C
307               Namibia            4.0            1.0            Group C
310                Zambia            4.0            0.0            Group D
320          Burkina Faso            4.0            4.0  Third place match
338          Burkina Faso            4.0            2.0            Group C
340               Tunisia            4.0            2.0            Group D
400              Zimbabwe            5.0            3.0            Group C
406          South Africa            4.0            0.0            Group D
407                 Benin            4.0            0.0            Group D
415                  Mali            4.0            0.0        Semi-finals
430                Zambia            4.0            1.0            Group C
443              DR Congo            4.0            1.0     Quarter-finals
458                 Benin            4.0            1.0            Group B
462              Cameroon            4.0            2.0            Group C
464                Zambia            5.0            1.0            Group C
475                Guinea            5.0            0.0     Quarter-finals
480           Ivory Coast            4.0            2.0  Third place match
482                  Mali            4.0            4.0            Group A
595            Mauritania            4.0            1.0            Group E

                SpecialWinConditions                       Stadium  \
2                                NaN             Municipal Stadium
3                                NaN         Prince Farouk Stadium
6                                NaN        Hailé Sélassié Stadium
9              win after extra time         Hailé Sélassié Stadium
12                               NaN          Accra Sports Stadium
13                               NaN         Kumasi Sports Stadium
15                               NaN         Kumasi Sports Stadium
18                               NaN          Stade Chedli Zouiten
20                               NaN          Stade Chedli Zouiten
21                               NaN         Stade Bou Ali Lahouar
23                               NaN             Stade Ahmed Bsiri
29                               NaN        Hailé Sélassié Stadium
39             win after extra time                 Cicero Stadium
46                               NaN             Municipal Stadium
49                               NaN            Wad Madani Stadium
69                               NaN     Stade de la Réunification
72                               NaN              Stade Omnisports
85                               NaN      Ala'ab Damanhour Stadium
97                               NaN             Dire Dawa Stadium
106                              NaN           Addis Ababa Stadium
110                              NaN          Accra Sports Stadium
159                              NaN  Stade Félix Houphouët-Boigny
205                              NaN          Stade 5 Juillet 1962
245                              NaN          Stade Chedli Zouiten
247                              NaN     Stade Olympique de Sousse
258                              NaN               Stade El Menzah
270                              NaN            Free State Stadium
272                              NaN            Free State Stadium
303                              NaN               Stade Municipal
306                              NaN               Stade Municipal
307                              NaN               Stade Municipal
310                              NaN               Stade Municipal
320  DR Congo  win on Penalities 4-1               Stade Municipal
338                              NaN           Sani Abacha Stadium
340                              NaN              National Stadium
400                              NaN          Stade Taïeb El Mhiri
406                              NaN     Stade Mustapha Ben Jannet
407                              NaN          Stade Taïeb El Mhiri
415                              NaN     Stade Olympique de Sousse
430                              NaN      Harras El-Hedoud Stadium
443                              NaN   Cairo International Stadium
458                              NaN               Sekondi Stadium
462                              NaN             Baba Yara Stadium
464                              NaN             Baba Yara Stadium
475                              NaN               Sekondi Stadium
480                              NaN             Baba Yara Stadium
482                              NaN        Estádio 11 de Novembro
595                              NaN                  Suez Stadium

                  City  Attendance
2             Khartoum     30000.0
3                Cairo     30000.0
6          Addis Ababa     30000.0
9          Addis Ababa         NaN
12               Accra         NaN
13              Kumasi         NaN
15              Kumasi         NaN
18               Tunis     16000.0
20               Tunis         NaN
21              Sousse         NaN
23             Bizerte         NaN
29         Addis Ababa     25000.0
39              Asmara      5000.0
46            Khartoum      9770.0
49          Wad Medani      7525.0
69              Douala         NaN
72             Yaoundé         NaN
85           Damanhour         NaN
97           Dire Dawa         NaN
106        Addis Ababa         NaN
110              Accra     50000.0
159            Abidjan     15000.0
205            Algiers     85000.0
245              Tunis      6000.0
247             Sousse     10000.0
258              Tunis      2000.0
270       Bloemfontein      2000.0
272       Bloemfontein       200.0
303     Bobo-Dioulasso     20000.0
306        Ouagadougou      4000.0
307     Bobo-Dioulasso      9500.0
310     Bobo-Dioulasso      5000.0
320        Ouagadougou     25000.0
338               Kano     17000.0
340              Lagos     80000.0
400               Sfax     15000.0
406           Monastir     15000.0
407               Sfax     20000.0
415             Sousse     15000.0
430         Alexandria     16000.0
443              Cairo     74000.0
458   Sekondi-Takoradi     13000.0
462             Kumasi     42000.0
464             Kumasi     10000.0
475            Sekondi     14000.0
480             Kumasi     40000.0
482             Luanda     45000.0
595               Suez      6202.0

In [320]:
# 8) change the “AwayTeamGoals” in the 3rd row to 10.
data.at[2, 'AwayTeamGoals'] = 10
# data
print(data)

     Year                      Date   Time      HomeTeam       AwayTeam  \
0    1957                  10-Feb-57    NaN       Sudan           Egypt
1    1957                  10-Feb-57    NaN    Ethiopia    South Africa
2    1957                  16-Feb-57    NaN       Egypt        Ethiopia
3    1959                  22-May-59    NaN        Egypt       Ethiopia
4    1959                  25-May-59    NaN       Sudan        Ethiopia
..    ...                        ...    ...          ...            ...
617  2019  11 July 2019 (2019-07-11)  21:00  Madagascar         Tunisia
618  2019  14 July 2019 (2019-07-14)  18:00     Senegal         Tunisia
619  2019  14 July 2019 (2019-07-14)  21:00     Algeria         Nigeria
620  2019  17 July 2019 (2019-07-17)  21:00     Tunisia         Nigeria
621  2019  19 July 2019 (2019-07-19)  21:00     Senegal         Algeria

     HomeTeamGoals  AwayTeamGoals                 Stage  \
0              1.0            2.0            Semifinals
1              NaN            NaN            Semifinals
2              4.0           10.0                 Final
3              4.0            0.0      Final Tournament
4              1.0            0.0      Final Tournament
..             ...            ...                   ...
617            0.0            3.0        Quarter-finals
618            1.0            0.0           Semi-finals
619            2.0            1.0           Semi-finals
620            0.0            1.0  Third place play-off
621            0.0            1.0                 Final

                                  SpecialWinConditions  \
0                                                  NaN
1    Ethiopia  wins due to disqualification of othe...
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
617                                                NaN
618                              win after extra time
619                                                NaN
620                                                NaN
621                                                NaN

                         Stadium       City  Attendance
0              Municipal Stadium   Khartoum     30000.0
1                            NaN        NaN         NaN
2              Municipal Stadium   Khartoum     30000.0
3          Prince Farouk Stadium      Cairo     30000.0
4          Prince Farouk Stadium      Cairo     20000.0
..                           ...        ...         ...
617             Al Salam Stadium      Cairo      7568.0
618              30 June Stadium      Cairo      9143.0
619  Cairo International Stadium      Cairo     49775.0
620             Al Salam Stadium      Cairo      6340.0
621  Cairo International Stadium      Cairo     75000.0

[622 rows x 12 columns]

In [321]:
# 9) sort the DataFrame first by ‘HomeTeam’ in ascending order, then by ‘HomeTeamScores’ in descending order.
data.sort_values(by=['HomeTeam','HomeTeamGoals'], ascending=[True, False]).head(3)

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
205,1990,2-Mar-90,NaN,Algeria,Nigeria,5.0,1.0,Group A,NaN,Stade 5 Juillet 1962,Algiers,85000.0
29,1968,14-Jan-68,NaN,Algeria,Uganda,4.0,0.0,Group A,NaN,Hailé Sélassié Stadium,Addis Ababa,25000.0
135,1980,16-Mar-80,NaN,Algeria,Guinea,3.0,2.0,Group B,NaN,Liberty Stadium,Ibadan,20000.0

In [322]:
# 10) get list from DataFrame column headers.
col_list_headers = data.columns.values
print(col_list_headers)

['Year' 'Date ' 'Time ' 'HomeTeam' 'AwayTeam' 'HomeTeamGoals'
 'AwayTeamGoals' 'Stage' 'SpecialWinConditions' 'Stadium' 'City'
 'Attendance']

In [323]:
# # 11) append a column of your choice to your DataFrame.
# data['Sequence']
# data.columns.values

In [324]:
# 12) add 2 rows to your DataFrame.
row_one = [1962, '18-Jan-64', None, 'Ghana', 'Uganda', 2, 1, 'Semifinals', None, 'Namboole Stadium', 'Addis Ababa', 30000]

row_two = [1959, '18-Jan-64', None, 'Ghana', 'Uganda', 2, 1, 'Semifinals', None, 'Namboole Stadium', 'Kampala', 30000]
data.loc[len(data.index)] = row_one
display(data.tail(5))

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
618,2019,14 July 2019 (2019-07-14),18:00,Senegal,Tunisia,1.0,0.0,Semi-finals,win after extra time,30 June Stadium,Cairo,9143.0
619,2019,14 July 2019 (2019-07-14),21:00,Algeria,Nigeria,2.0,1.0,Semi-finals,NaN,Cairo International Stadium,Cairo,49775.0
620,2019,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0
621,2019,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0
622,1962,18-Jan-64,None,Ghana,Uganda,2.0,1.0,Semifinals,None,Namboole Stadium,Addis Ababa,30000.0

In [325]:
# 13) change the country ‘Uganda’ to ‘China’ in the ‘AwayTeam’ column of the DataFrame.
# columns_headers = data.columns.values
data.loc[data['AwayTeam'].str.strip()=='Uganda']='China'
print(data.head(20))

     Year      Date   Time    HomeTeam       AwayTeam HomeTeamGoals  \
0    1957  10-Feb-57    NaN     Sudan           Egypt           1.0
1    1957  10-Feb-57    NaN  Ethiopia    South Africa           NaN
2    1957  16-Feb-57    NaN     Egypt        Ethiopia           4.0
3    1959  22-May-59    NaN      Egypt       Ethiopia           4.0
4    1959  25-May-59    NaN     Sudan        Ethiopia           1.0
5    1959  29-May-59    NaN      Egypt          Sudan           2.0
6    1962  14-Jan-62    NaN  Ethiopia         Tunisia           4.0
7   China      China  China      China          China         China
8   China      China  China      China          China         China
9    1962  21-Jan-62    NaN  Ethiopia           Egypt           4.0
10   1963  24-Nov-63    NaN     Ghana         Tunisia           1.0
11   1963  26-Nov-63    NaN     Ghana        Ethiopia           2.0
12   1963  28-Nov-63    NaN  Ethiopia         Tunisia           4.0
13   1963  24-Nov-63    NaN      Egypt        Nigeria           6.0
14   1963  26-Nov-63    NaN      Egypt          Sudan           2.0
15   1963  28-Nov-63    NaN     Sudan         Nigeria           4.0
16   1963  30-Nov-63    NaN      Egypt       Ethiopia           3.0
17   1963   1-Dec-63    NaN     Ghana           Sudan           3.0
18   1965  12-Nov-65    NaN   Tunisia        Ethiopia           4.0
19   1965  14-Nov-65    NaN   Senegal         Tunisia           0.0

   AwayTeamGoals              Stage  \
0            2.0         Semifinals
1            NaN         Semifinals
2           10.0              Final
3            0.0   Final Tournament
4            0.0   Final Tournament
5            1.0   Final Tournament
6            2.0         Semifinals
7          China              China
8          China              China
9            2.0              Final
10           1.0            Group A
11           0.0            Group A
12           2.0            Group A
13           3.0            Group B
14           2.0            Group B
15           0.0            Group B
16           0.0  Third place match
17           0.0              Final
18           0.0            Group A
19           0.0            Group A

                                 SpecialWinConditions                 Stadium  \
0                                                 NaN       Municipal Stadium
1   Ethiopia  wins due to disqualification of othe...                     NaN
2                                                 NaN       Municipal Stadium
3                                                 NaN   Prince Farouk Stadium
4                                                 NaN   Prince Farouk Stadium
5                                                 NaN   Prince Farouk Stadium
6                                                 NaN  Hailé Sélassié Stadium
7                                               China                   China
8                                               China                   China
9                               win after extra time   Hailé Sélassié Stadium
10                                                NaN    Accra Sports Stadium
11                                                NaN    Accra Sports Stadium
12                                                NaN    Accra Sports Stadium
13                                                NaN   Kumasi Sports Stadium
14                                                NaN   Kumasi Sports Stadium
15                                                NaN   Kumasi Sports Stadium
16                                                NaN    Accra Sports Stadium
17                                                NaN    Accra Sports Stadium
18                                                NaN    Stade Chedli Zouiten
19                                                NaN    Stade Chedli Zouiten

            City Attendance
0       Khartoum    30000.0
1            NaN        NaN
2       Khartoum    30000.0
3          Cairo    30000.0
4          Cairo    20000.0
5          Cairo    30000.0
6    Addis Ababa    30000.0
7          China      China
8          China      China
9    Addis Ababa        NaN
10         Accra        NaN
11         Accra        NaN
12         Accra        NaN
13        Kumasi        NaN
14        Kumasi        NaN
15        Kumasi        NaN
16         Accra        NaN
17         Accra        NaN
18         Tunis    16000.0
19         Tunis        NaN

/tmp/ipykernel_6539/2257079760.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'China' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[data['AwayTeam'].str.strip()=='Uganda']='China'
/tmp/ipykernel_6539/2257079760.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'China' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data.loc[data['AwayTeam'].str.strip()=='Uganda']='China'
/tmp/ipykernel_6539/2257079760.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'China' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data.loc[data['AwayTeam'].str.strip()=='Uganda']='China'
/tmp/ipykernel_6539/2257079760.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'China' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data.loc[data['AwayTeam'].str.strip()=='Uganda']='China'

In [326]:
# 14) reset index in your DataFrame.
data = pd.read_csv('data/AfricaCupofNationsMatches.csv')
# data.head(3)
data.set_index(['Year','HomeTeamGoals'])
print(data.index)
data.reset_index(drop=False)

RangeIndex(start=0, stop=622, step=1)

,index,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0
1,1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
2,2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
4,4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
617,617,2019,11 July 2019 (2019-07-11),21:00,Madagascar,Tunisia,0.0,3.0,Quarter-finals,NaN,Al Salam Stadium,Cairo,7568.0
618,618,2019,14 July 2019 (2019-07-14),18:00,Senegal,Tunisia,1.0,0.0,Semi-finals,win after extra time,30 June Stadium,Cairo,9143.0
619,619,2019,14 July 2019 (2019-07-14),21:00,Algeria,Nigeria,2.0,1.0,Semi-finals,NaN,Cairo International Stadium,Cairo,49775.0
620,620,2019,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0
621,621,2019,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0

In [376]:

df = pd.DataFrame({'name':['John', 'Joan','Edgar'],'age':[34,12,67], 'class':['p1','p2','p3']}, index=['a','b','c'])


print(df)
# df.set_index(['age','class'])
df.reset_index(drop=True)

    name  age class
a   John   34    p1
b   Joan   12    p2
c  Edgar   67    p3

    name  age class
0   John   34    p1
1   Joan   12    p2
2  Edgar   67    p3